etheme: jekyll-theme-cayman
title: Maze Benchmark for Evolutionary Algorithms
desciption: web page for all supplementary material

github:
  zip_url: https://github.com/mazebenchmark/mazebenchmark.github.io/raw/master/download/dataset.zip
  executable_url: https://github.com/mazebenchmark/mazebenchmark.github.io/raw/master/download/MazeGenerator.jar
